### ISSUE TITLE
Popping the backstack from navController doesn't trigger the standard hide animation

### ISSUE THREAD

**Issue by pablobaldez** [stefanoq21/BottomSheetNavigator3#5] opened 2024-08-16 19:51 UTC
When calling `navController.popBackStack` I would expected that the bottom sheet would hide itself such as it happens when I press the device's back button.
However, this is not what happens. The animation is the default one (just a fadeout)

Actual (popping the backstack from navController) | Expected (pressing the device button) |
------------ | ------------- |
<video src="https://github.com/user-attachments/assets/b6eb104c-7876-4143-89ac-6842c46eee1e" width="300"/> | <video src="https://github.com/user-attachments/assets/93681578-d208-43b1-9568-11b2ec6b8e77" width="300"/>

**Comment by pablobaldez** [comment] 2024-08-16 19:59
And I noticed that after the first `navController.popBackStack`, even the entering animation is not triggered. 
I need to press the device's back button again to make the bottomsheet animation come back
<video src="https://github.com/user-attachments/assets/3883bb03-6a31-4552-8060-b9fb087e8e5b" width="300"/>.
Here you can see I'm pressing the device's button to navigate back for the first times.
Then when I click in the screen's button, the navController is triggered and the navigation stop to work.

**Comment by stefanoq21** [comment] 2024-08-16 20:37
Hi @pablobaldez thanks for your message. I will check your problem as soon as possible. Can you confirm the version you are using is the 0.0.5? Thanks again.

**Comment by pablobaldez** [comment] 2024-08-16 21:16
I did this test cloning your repo and applying changes in the sample app you have in the project.

**Comment by pablobaldez** [comment] 2024-08-16 21:17
And I think I have the fix for it as well

**Comment by stefanoq21** [comment] 2024-08-17 08:21
Hi @pablobaldez, the issue is fixed in version 0.0.6. I had already addressed it in the KMP version but I didn't propagate the fix there. Thanks for your interest!

**Closed by stefanoq21** 2024-08-17 08:21 UTC
