### ISSUE TITLE
BackHandler doesn't invoke when PredictiveBackGestures are enabled!

### ISSUE THREAD

**Issue by RezaDizaji** [stefanoq21/BottomSheetNavigator3#9] opened 2024-10-11 15:14 UTC
As mentioned in the title, unfortunately, I discovered that BackHandler doesn't work when predictive back gestures are enabled.

**Comment by stefanoq21** [comment] 2024-10-12 07:19
Hi @RezaDizaji, 
I will check it and let you know.
Thanks

**Comment by stefanoq21** [comment] 2024-10-12 07:37
Hi @RezaDizaji,

I've tested the sample app with PredictiveBackGestures enabled and everything seems to be working correctly. Could you please try again or provide more details about the issue you're encountering?

Thanks

**Comment by RezaDizaji** [comment] 2024-10-12 09:58
Hi dear Stephan,

I'll try to collect more information regarding the issue and add to this thread.

Thanks for your fast responses, as always. 👌🏻👍🏻

________________________________

**Comment by stefanoq21** [comment] 2024-10-19 08:16
Hi @RezaDizaji,
I'm closing the issue for now as it seems to be not a bug. In case you find something new fill free to open a new issue. 
Thanks.

**Closed by stefanoq21** 2024-10-19 08:16 UTC
